name: Build Service Bundle and Deploy to Lambda Functions

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - "catalog/**" # Only run if files inside the 'catalog' directory have changed.

jobs:
  was_merged:
    name: "Only Run When Merged"
    # This job is cancelled if the pull request was closed rather than merged.
    # To prevent the rest of this workflow from running, the first job(s) in
    # the workflow should have a `needs: was_merged` attribute.
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Pull request merged."

  version:
    name: "Get Version Tag"
    runs-on: ubuntu-latest
    needs: was_merged
    outputs:
      version_tag: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          # ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history

      - uses: codacy/git-version@2.8.0
        # This action can be configured to bump monorepo modules separately if needed.
        # See docs at https://github.com/marketplace/actions/git-version
        id: version
        with:
          release-branch: main
          minor-identifier: "[semver:minor]"
          major-identifier: "[semver:major]"
          prefix: v

      - run: |
          git config --global user.email "robot@berg.industries"
          git config --global user.name "Github Automated Workflow"
          git tag -m '${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})' ${{ steps.version.outputs.version }} '${{ github.base_ref }}'
          git push origin ${{ steps.version.outputs.version }}

  # test:
  #   name: Run Unit Tests
  #   runs-on: ubuntu-latest

  upload:
    runs-on: ubuntu-latest
    environment: "Production"
    needs:
      - was_merged
      - version

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Latest Revisions
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE_GITHUB_ACTIONS_DEPLOY }}
          role-session-name: "GithubActionsDeploy"
          aws-region: us-east-2

      - name: Build and Deploy Catalog Service
        uses: ./.github/actions/build_push.yaml
        with:
          base_dir: catalog
          version: ${{ needs.version.outputs.version_tag }}
          tag_as_latest: false
